services:
  npm-service:
    image: npm-course-03-11
    build: .
    container_name: 03-11-npm
    ports:
      - "8081:53682"
    volumes:
      - ./11-passing-functions-as-values/:/src
    entrypoint: "tail"
    command: ["-f", "/dev/null"]